export const LOADING = 'LOADING';
export const SUCCESS = 'SUCCESS';
export const ERROR = 'ERROR';
export const ERROR_DISMISS = 'ERROR_DISMISS';
export const REDIRECT_LOGIN = 'REDIRECT_LOGIN';
export const REMOVE_USER_REGISTER_DATA = 'REMOVE_USER_REGISTER_DATA';